### PR TITLE
bot.js

### PR DESCRIPTION
**Pull request by dakotamurphyucf**

### CODE REVIEW

**Comment by nathang21** [comment]
Did you cancel this Pull Request?

That's fine, cause your local repository was out of sync. We'll have to teach you how to git pull / git fetch the latest changes before pushing.

For now i'd just stay on your branch, you can still push your local dakota (cloud9) branch to the remote dakota (github) branch for changes.

Hope that makes sense.

**Comment by bluezeb12** [comment]
I'll try to help explain, and walk through the git hub workflow tonight
when Dakota comes over.

**Comment by nathang21** [comment]
Sweet.

I was just confused what happened, cause I saw the pull request, but it said closed, yet it doesn't look like it was merged. Not sure how that works exactly, but that means canceled right?

**Comment by bluezeb12** [comment]
Yeah. I believe that's what that means

**Comment by bluezeb12** [comment]
Joe Landry has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=366668462857-3qkidqn8oseh9v3fhm3085kpb747bgm7.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.gdocs.download%2Fg.php&customparam=customparam>

**Pull request closed without merging**
